### ISSUE TITLE
Not published to jcenter

### ISSUE THREAD

**Issue by bearrito** [jacek99/structlog4j#1]
This does not look like it has been published to jcenter.

**Comment by jacek99** [comment]
Can you check now? 1.0.0 is definitely there

**Comment by fjaweihyafei** [comment]
I am using maven, and I configured the dependencies as you described. But I got the error: 
The POM for structlog4j:structlog4j-api:jar:1.0.0 is missing, no depency information available
The POM for structlog4j:structlog4j-json:jar:1.0.0 is missing, no depency information available
So I cannot use your jar package, could you check again?

**Comment by jacek99** [comment]
OK, let me check tomorrow.

Sorry for the delay in answering your initial call, my notiifications were off by mistake for this repo....

**Comment by solsson** [comment]
@jacek99 Same here. Gradle says:
```
Could not resolve: structlog4j:structlog4j-api:1.0.0
Could not resolve: structlog4j:structlog4j-json:1.0.0
```

**Comment by jacek99** [comment]
OK, will try to look at this ASAP later today...weird, because I see it in
the bintray jcenter dashboard

**Comment by jacek99** [comment]
Sorry, my bad. I uploaded it to Bintray, but forgot for this new repo to link it to JCenter, so they never pushed it there. Working on fixing it now, sorry for the mixup

**Comment by jacek99** [comment]
I believe temporarily you can use this:

```
repositories { 
    maven { 
        url "http://dl.bintray.com/jacek99/structlog4j" 
    }
}
```

until JCenter approves my requests....

**Comment by solsson** [comment]
Thanks a lot 
```
repositories {
  ...
  maven {
    url "http://dl.bintray.com/jacek99/structlog4j"
  }
}

dependencies {
  ...
  compile group: 'structlog4j', name: 'structlog4j-api', version: '1.0.0'
  compile group: 'structlog4j', name: 'structlog4j-json', version: '1.0.0'
}
```

I've evaluated structlog4j now and [we](https://github.com/Yolean/)'ll be replacing slf4j with this API. With developers coming from mostly javascript the placeholder format of slf4j is really awkward. I like both the key-value and the JSON output from this lib, but more importantly our log statements will be easy to read and maintainable. Maintainability was never a strength of the slf4j API, because over time you'd get mismatches between placeholders and arguments, resulting in confusion when reading logs.

**Comment by jacek99** [comment]
The jcenter approval went through, everything should work now with base jcenter()

Thanks for checking out the library @solsson, really excited to see someone use it in production.
Hit me up with any comments or issues you find, want to make sure it is useful.

**Comment by solsson** [comment]
Yes `jcenter()` works now.
