### ISSUE TITLE
settings? Output to file/console?log level?...

### ISSUE THREAD

**Issue by fjaweihyafei** [jacek99/structlog4j#3]
I followed your document, but there is nothing output, and no errors. Could you tell me how to configure the log file path, log level ... There is no settings for it?

**Comment by jacek99** [comment]
It's on top of SLF4J. So just use whatever SLFJ setup you already have (over log4j, logback, etc).

**Comment by jacek99** [comment]
It's designed to integrate into any existing app that already runs logging on top of SLF4J. If you look at the code, all it does is relegate the actual logging to the standard SLF4J API, just ensures the log message is properly structured
