### ISSUE TITLE
你这个库，我用logger.info(...)后，怎么看输出的log啊？

### ISSUE THREAD

**Issue by jxr202** [jacek99/structlog4j#7]
我的 android 项目用maven 方式引入了你的库，然后在MainActivity里面调用了logger.info()方法，但 android studio LogCat控制台没有对应的log输出呀？

**Comment by jacek99** [comment]
Sorry, I don't speak Chinese. Could you post this in English?

Thank you.

**Comment by jacek99** [comment]
Closing due to lack of response
